In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

#loading a pretrained model and a tokenizer using HuggingFace
tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")

# Create a partial sentence and tokenize it.
text = "Computer science is related to Robotics"
inputs = tokenizer(text, return_tensors="pt")

# Show the tokens as numbers, i.e. "input_ids"
inputs["input_ids"]

tensor([[34556,  3783,   318,  3519,   284, 47061]])

In [ ]:
# Show how the sentence is tokenized
import pandas as pd


def show_tokenization(inputs):
    return pd.DataFrame(
        [(id, tokenizer.decode(id)) for id in inputs["input_ids"][0]],
        columns=["id", "token"],
    )


show_tokenization(inputs)

              id      token
0  tensor(34556)   Computer
1   tensor(3783)    science
2    tensor(318)         is
3   tensor(3519)    related
4    tensor(284)         to
5  tensor(47061)   Robotics

In [ ]:
# Calculate the probabilities for the next token for all possible choices. We show the
# top 5 choices and the corresponding words or subwords for these tokens.

import torch

with torch.no_grad():
    logits = model(**inputs).logits[:, -1, :]
    probabilities = torch.nn.functional.softmax(logits[0], dim=-1)


def show_next_token_choices(probabilities, top_n=5):
    return pd.DataFrame(
        [
            (id, tokenizer.decode(id), p.item())
            for id, p in enumerate(probabilities)
            if p.item()
        ],
        columns=["id", "token", "p"],
    ).sort_values("p", ascending=False)[:top_n]


show_next_token_choices(probabilities)

      id token         p
290  290   and  0.247134
11    11     ,  0.241039
13    13     .  0.163842
287  287    in  0.056530
357  357     (  0.019930

In [ ]:
# Obtain the token id for the most probable next token
next_token_id = torch.argmax(probabilities).item()

print(f"Next token id: {next_token_id}")
print(f"Next token: {tokenizer.decode(next_token_id)}")

Next token id: 290
Next token:  and

In [ ]:
# We append the most likely token to the text.
text = text + tokenizer.decode(8300)
text

'Computer science is related to Robotics programming'

In [ ]:
from IPython.display import Markdown, display

# Show the text
print(text)

# Convert to tokens
inputs = tokenizer(text, return_tensors="pt")

# Calculate the probabilities for the next token and show the top 5 choices
with torch.no_grad():
    logits = model(**inputs).logits[:, -1, :]
    probabilities = torch.nn.functional.softmax(logits[0], dim=-1)

display(Markdown("**Next token probabilities:**"))
display(show_next_token_choices(probabilities))

# Choose the most likely token id and add it to the text
next_token_id = torch.argmax(probabilities).item()
text = text + tokenizer.decode(next_token_id)

Computer science is related to Robotics programming

**Next token probabilities:**

        id       token         p
13      13           .  0.278752
11      11           ,  0.216728
290    290         and  0.104445
287    287          in  0.058708
8950  8950   languages  0.029115

In [ ]:
# use the generated method

from IPython.display import Markdown, display

# Start with some text and tokenize it
text = "Generative programming"
inputs = tokenizer(text, return_tensors="pt")

# Use the `generate` method to generate lots of text
output = model.generate(**inputs, max_length=100, pad_token_id=tokenizer.eos_token_id)

# Show the generated text
display(Markdown(tokenizer.decode(output[0])))

Generative programming is a new way of thinking about programming. It's a way of thinking about programming that is not just about programming, but about the way we think about programming.

The first thing that I want to say is that I think that the way we think about programming is not just about programming, but about the way we think about programming.

I think that the way we think about programming is not just about programming, but about the way we think about programming.